name: pre-commit

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
 pre-commit:
    strategy:
      matrix:
        python-version: ["3.8"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install -y libnlopt-dev;
          fi
          if [ "$RUNNER_OS" == "macOS" ]; then
          brew install nlopt;
          fi
          python3 -m pip install --upgrade pip setuptools wheel
          pip install --upgrade click==8.0.2
          pip install numpy
          pip install  -e .[all,pre-commit,testing]
          pip freeze
      - name: Run pre-commit
        run:
          pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
